Repository 2025Capstone/Frontend, pull requests merged in 2025-04, with the labels that each got.

#11 Junyou
  package-lock.json
  package.json
  public/index.html
  src/App.css
  src/App.tsx
  src/components/Root.tsx
  src/components/Router.tsx
  src/screen/student/Analysis.tsx
  src/screen/student/Chat.tsx
  src/screen/student/Lecture.tsx
  src/screen/student/Lectures.tsx
  src/screen/student/Main.tsx
  src/screen/student/Setting.tsx
Labels: ✨ enhancement

#16 [feat]: 교수자 강의 녹화 페이지 구현
  .github/pull_request_template.md
  src/screen/lecturer/Lectures.tsx
Labels: ✨ feat, 🔥 priority: high

#17 [feat]: 영상 업로드 API 호출 코드 추가 (#14)
  src/screen/lecturer/RecordingDetail.tsx
Labels: ✨ feat, 🔥 priority: high, 🚨 help
